import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("train.csv")
k = df.to_numpy()
x1 = k[:,0]
x2 = k[:,1]
x3 = k[:,2]
x4 = k[:,3]
x5 = k[:,4]
x6 = k[:,5]
t = k [:,6]
plt.plot(x1,x2,'.')
plt.xlabel("x1 values")
plt.ylabel("x2 values")
plt.show()
plt.plot(x1,x3,'.')
plt.xlabel("x1 values")
plt.ylabel("x3 values")
plt.show()
plt.plot(x1,x4,'.')
plt.xlabel("x1 values")
plt.ylabel("x4 values")
plt.show()
plt.plot(x1,x5,'.')
plt.xlabel("x1 values")
plt.ylabel("x5 values")
plt.show()
plt.plot(x1,x6,'.')
plt.xlabel("x1 values")
plt.ylabel("x6 values")
plt.show()
plt.plot(x2,x3,'.')
plt.xlabel("x2 values")
plt.ylabel("x3 values")
plt.show()
plt.plot(x2,x4,'.')
plt.xlabel("x2 values")
plt.ylabel("x4 values")
plt.show()
plt.plot(x2,x5,'.')
plt.xlabel("x2 values")
plt.ylabel("x5 values")
plt.show()
plt.plot(x2,x6,'.')
plt.xlabel("x2 values")
plt.ylabel("x6 values")
plt.show()
plt.plot(x3,x4,'.')
plt.xlabel("x3 values")
plt.ylabel("x4 values")
plt.show()
plt.plot(x3,x5,'.')
plt.xlabel("x3 values")
plt.ylabel("x5 values")
plt.show()
plt.plot(x3,x6,'.')
plt.xlabel("x3 values")
plt.ylabel("x6 values")
plt.show()
plt.plot(x4,x5,'.')
plt.xlabel("x4 values")
plt.ylabel("x5 values")
plt.show()
plt.plot(x4,x6,'.')
plt.xlabel("x4 values")
plt.ylabel("x6 values")
plt.show()
plt.plot(x5,x6,'.')
plt.xlabel("x5 values")
plt.ylabel("x6 values")
plt.show()
plt.plot(x1,t,'.')
plt.xlabel("x1 values")
plt.ylabel("t values")
plt.show()
plt.plot(x2,t,'.')
plt.xlabel("x2 values")
plt.ylabel("t values")
plt.show()
plt.plot(x3,t,'.')
plt.xlabel("x3 values")
plt.ylabel("t values")
plt.show()
plt.plot(x4,t,'.')
plt.xlabel("x4 values")
plt.ylabel("t values")
plt.show()
plt.plot(x5,t,'.')
plt.xlabel("x5 values")
plt.ylabel("t values")
plt.show()
plt.plot(x6,t,'.')
plt.xlabel("x6 values")
plt.ylabel("t values")
plt.show()
dataframe = pd.DataFrame(df, columns=['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 't'])
matrix = dataframe.corr()
# print("Correlation matrix is : ")
print(matrix)

